In [1]:
import numpy as np

In [6]:
g = np.zeros(10)

In [7]:
g[2]=1
g[4]=1
g[7]=.3

In [8]:
g

array([0. , 0. , 1. , 0. , 1. , 0. , 0. , 0.3, 0. , 0. ])

In [15]:
mask = g == 0

In [10]:
e = np.random.random(10)

In [21]:
e[a]

array([0.64080046, 0.89461737, 0.60585269, 0.10032836, 0.81754554,
       0.80716607, 0.85271151])

In [16]:
mask

array([ True,  True, False,  True, False,  True,  True, False,  True,
        True])

In [18]:
a = []

In [19]:
a.extend(mask)

In [20]:
a

[True, True, False, True, False, True, True, False, True, True]